const yaml = require('js-yaml');
const fs = require('fs');
const { v4: uuidv4 } = require('uuid');
const doc = yaml.load(fs.readFileSync('src/report_template.yml','utf8'));
// console.log(uuidv4());
console.log(doc.data[1].id);
// const procCode="SNOMEDCT#NOMEDCT#25732003 Fiberoptic colonoscopy with biopsy (procedure)")); Fiberoptic colonoscopy with biopsy (procedure)";
// console.log(procCode.slice(0,17));
const polypectomyProcedureIndex = doc.data.findIndex(c => c.code.slice(0,18)==="SNOMEDCT#311774002");
doc.data[polypectomyProcedureIndex].id=uuidv4();
console.log(doc.data[polypectomyProcedureIndex].id);
console.log(doc.data[polypectomyProcedureIndex]);